### ISSUE TITLE
Background Blur

### ISSUE THREAD

**Issue by ddkk08001** [ddkk08001/krspaceinfo#2]
백그라운드 이미지에 블러 필터 씌우기

```
.header {
    background-image: url("../images/nuri3rdtake.jpg");
    background-size: cover;
    background-position: center center;
    height: 400px;
    margin-top: 70px;
    display: flex;
    align-items: center;
    justify-content: center;
}
```

css 에서 이런 백그라운드가 적용된 상태에서 블러를 씌울수 있는가

**Comment by Akashsingh310** [comment]
Yes, it is possible to apply a blur effect to the background image 

Try This
```css
.header {
    position: relative; 
    background-image: url("../images/nuri3rdtake.jpg");
    background-size: cover;
    background-position: center center;
    height: 400px;
    margin-top: 70px;
    display: flex;
    align-items: center;
    justify-content: center;
}

.header::before {
    content: "";
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background-image: url("../images/nuri3rdtake.jpg"); 
    background-size: cover;
    background-position: center center;
    filter: blur(10px); /* Adjust the blur amount as needed */
    opacity: 0.7; /* Adjust the overlay opacity*/
    z-index: -1; /* Place the overlay behind the content */
}
```

This is a blurred version of the same background image applied to it using the filter: blur() CSS property. You can adjust the blur amount and the overlay's opacity to achieve the desired effect and if you want the content to appear above the blurred background, make sure to use the appropriate z-index
